/**
 * 389. Find the Difference
Easy

2549

371

Add to List

Share
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
 */
package leetcode.company.google;

import java.util.HashMap;

public class FindTheDifference {

    public char findTheDifference(String s, String t) {
        HashMap < Character, Integer > map = new HashMap < Character, Integer > ();
        for (char ch: s.toCharArray()) {
            map.put(ch, map.getOrDefault(ch, 0) + 1);
        }
        for (char ch: t.toCharArray()) {
            if (!map.containsKey(ch) || map.get(ch) == 0) {
                return ch;
            }
            map.put(ch, map.getOrDefault(ch, 0) - 1);
        }
        return '0';
    }

    public static void main(String[] args) {
        // TODO Auto-generated method stub

    }

}