//time complexity: O(n + m)
//space complexity: O(c) --> c is the unique character in string
//https://leetcode.com/problems/find-the-difference/

/**
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Example 3:
Input: s = "a", t = "aa"
Output: "a"

Example 4:
Input: s = "ae", t = "aea"
Output: "a"
 */

package leetcode.string;

import java.util.HashMap;
import java.util.Map;

public class GenerateDocument {

    public static boolean generateDocument(String characters, String document) {
        Map < Character, Integer > map = new HashMap < Character, Integer > ();
        for (int i = 0; i < characters.length(); i++) {
            char ch = characters.charAt(i);
            map.put(ch, map.getOrDefault(ch, 0) + 1);
        }
        for (int i = 0; i < document.length(); i++) {
            char ch = document.charAt(i);
            if (!map.containsKey(ch) || map.get(ch) == 0) {
                return false;
            }
            map.put(ch, map.getOrDefault(ch, 0) - 1);
        }
        return true;
    }
    public static void main(String[] args) {
        // TODO Auto-generated method stub
        System.out.println(generateDocument("ae", "aea"));
    }

}